<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE usuarios [
  <!ELEMENT usuarios (usuario+)>
  <!ELEMENT usuario (nombre, password, rol)>
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT password (#PCDATA)>
  <!ELEMENT rol (#PCDATA)>
]>
<usuarios>
  <usuario id="1">
    <nombre>davidsossa@ftw.com</nombre>
    <password>libros123</password>
    <rol>admin</rol>
  </usuario>
</usuarios>